### ISSUE TITLE
README更新

### ISSUE THREAD

**Issue by zhujiem** [logpai/hybridlogparser#2]
1. 请参照loghub对数据集的来源及适用场景有一些简短的介绍。另外可添加一个表格说明行数、大小、模板数等基本信息。
2. 加上citation信息
3. 要添加外链的话直接在你的表格里加一列代码列给出[Link]https://github.com/Siyuexi/Hue
4. 如果要把代码放进本目录，需要在Hue目录下有demo脚本及README说明。或者建议该目录只放数据及外链到你的code repo
5. 请尽量让一个repo看起来美观、清晰。
@PinjiaHe @Siyuexi

**Comment by Siyuexi** [comment]
Thank you for the suggestions. We have incorporated the following changes based on the recommendations:

    1. We have provided a brief introduction to the source of the dataset and documented the dataset's details, such as the quantity of templates for each category, in the `README.md`.
    2. We have added citation information for the paper.
    3. External links have been placed in the references following the prescribed format.
    4. Following the guidelines, we have included a **demo** for the implementation of the Hue algorithm.

**Comment by zhujiem** [comment]
Well done. Thanks for the contribution!

**Comment by zhujiem** [comment]
A minor sugguestion: make the numbers in the table centered.

**Comment by zhujiem** [comment]
Additionally, please capitalize the first letter of the paper's title in the table.  Also, consider to provide a short introduction about the task of hybrid log parsing and clarify its difference to logparser.
